name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                #Run tests

            - name: Run tests
              run: |
                python -m unittest discover -s app -p "test_*.py"

    Docker:
        runs-on: ubuntu-latest
        needs: build
        steps: 
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Docker Hub 
              if: secrets.DOCKERHUB_SECRET && secrets.DOCKERHUB_USERNAME
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_SECRET }}

            - name: build Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                file: Dockerfile
                push: true
                tags: nihidocker/finance_app:latest